import os

import pytest

from okeyremap import privileged

posix_only = pytest.mark.skipif(os.name != "posix", reason="needs /bin/sh")


def test_the_elevator_can_be_overridden(monkeypatch):
    monkeypatch.setenv("OMARCHY_KEY_REMAP_ELEVATOR", "doas -n")
    assert privileged.elevator() == ["doas", "-n"]


def test_an_empty_override_is_ignored(monkeypatch):
    monkeypatch.setenv("OMARCHY_KEY_REMAP_ELEVATOR", "")
    monkeypatch.setattr(privileged.shutil, "which", lambda name: "/usr/bin/" + name)
    monkeypatch.setattr(privileged.sys.stdin, "isatty", lambda: False)
    monkeypatch.setattr(privileged.os, "geteuid", lambda: 1000, raising=False)
    assert privileged.elevator() == ["pkexec"]


@posix_only
def test_installing_writes_the_file_and_reloads(tmp_path, monkeypatch):
    """The whole privileged step, with `sh` standing in for sudo."""
    monkeypatch.setenv("OMARCHY_KEY_REMAP_ELEVATOR", "env")
    monkeypatch.setattr(privileged, "check", lambda text: (True, ""))
    target = tmp_path / "default.conf"
    # "env" stands in for sudo: a prefix that changes nothing and needs no password.
    privileged.install("# Generated by omarchy-key-remap\n[main]\ncapslock = esc\n",
                       reload=False, target=str(target))
    assert "capslock = esc" in target.read_text(encoding="utf-8")


@posix_only
def test_a_foreign_config_is_backed_up_before_it_is_replaced(tmp_path, monkeypatch):
    monkeypatch.setenv("OMARCHY_KEY_REMAP_ELEVATOR", "env")
    monkeypatch.setattr(privileged, "check", lambda text: (True, ""))
    target = tmp_path / "default.conf"
    target.write_text("[main]\nsomething = the_user_wrote\n", encoding="utf-8")

    privileged.install("# Generated by omarchy-key-remap\n[main]\ncapslock = esc\n",
                       reload=False, target=str(target))

    backups = list(tmp_path.glob("default.conf.bak-*"))
    assert len(backups) == 1
    assert "the_user_wrote" in backups[0].read_text(encoding="utf-8")
    assert "capslock = esc" in target.read_text(encoding="utf-8")


@posix_only
def test_our_own_config_is_not_backed_up_every_time(tmp_path, monkeypatch):
    monkeypatch.setenv("OMARCHY_KEY_REMAP_ELEVATOR", "env")
    monkeypatch.setattr(privileged, "check", lambda text: (True, ""))
    target = tmp_path / "default.conf"
    text = "# Generated by omarchy-key-remap\n[main]\ncapslock = esc\n"
    privileged.install(text, reload=False, target=str(target))
    privileged.install(text, reload=False, target=str(target))
    assert list(tmp_path.glob("default.conf.bak-*")) == []


def test_a_config_keyd_rejects_never_reaches_the_disk(tmp_path, monkeypatch):
    monkeypatch.setenv("OMARCHY_KEY_REMAP_ELEVATOR", "/bin/false")
    monkeypatch.setattr(privileged, "check", lambda text: (False, "line 3: nonsense"))
    target = tmp_path / "default.conf"
    with pytest.raises(privileged.PrivilegeError) as e:
        privileged.install("whatever", target=str(target))
    assert "nonsense" in str(e.value)
    assert not target.exists()
