"""Turning a list of remaps into a keyd config — and into runtime bindings.

Everything here is a pure function over Remap objects, so the whole generator can be
tested without keyd, without root and without a keyboard. What it produces is then
handed to `keyd check` before it is allowed anywhere near /etc.
"""
from __future__ import annotations

from dataclasses import dataclass, field

from .keys import KeyError_, layer_for, parse_combo, validate_action

HEADER = """\
# Generated by omarchy-key-remap. Do not edit by hand: the next
# `omarchy-key-remap apply` overwrites this file.
#
# Remaps live in ~/.config/omarchy-key-remap/remaps.json.
# If a remap ever leaves the machine unusable, hold backspace+escape+enter
# together — keyd exits and the keyboard goes back to normal.
"""


@dataclass
class Remap:
    """One line of the user's intent: this combination now does that."""
    source: str                       # "capslock", "ctrl+shift+c"
    action: str                       # "esc", "C-insert", "macro(C-g n)", "command(...)"
    app: str | None = None            # a window class; None means everywhere
    note: str = ""

    def validate(self) -> "Remap":
        parse_combo(self.source)
        validate_action(self.action)
        if self.app is not None and not self.app.strip():
            raise KeyError_("the app may not be blank — leave it out for a global remap")
        return self

    @property
    def key(self) -> str:
        """What makes two remaps the same remap: the same keys, in the same app."""
        mods, key = parse_combo(self.source)
        return f"{self.app or ''}:{'+'.join((*mods, key))}"

    def to_json(self) -> dict:
        out = {"from": self.source, "to": self.action}
        if self.app:
            out["app"] = self.app
        if self.note:
            out["note"] = self.note
        return out

    @classmethod
    def from_json(cls, data: dict) -> "Remap":
        return cls(source=data.get("from", ""), action=data.get("to", ""),
                   app=data.get("app") or None, note=data.get("note", ""))


def binding(remap: Remap) -> str:
    """One keyd binding expression: "capslock = esc" or "control+shift.c = C-insert".

    This is both what a config line looks like inside its section and what
    `keyd bind` takes, which is why the per-app watcher can reuse it verbatim.
    """
    mods, key = parse_combo(remap.source)
    prefix = f"{layer_for(mods)}." if mods else ""
    return f"{prefix}{key} = {remap.action}"


def generate(remaps: list[Remap], ids: str = "*") -> str:
    """The whole /etc/keyd/default.conf for the global (app-less) remaps."""
    globals_ = [r.validate() for r in remaps if not r.app]

    sections: dict[str, list[tuple[Remap, str, str]]] = {}
    for r in globals_:
        mods, key = parse_combo(r.source)
        sections.setdefault(layer_for(mods), []).append((r, key, r.action))

    out = [HEADER, "[ids]", "", ids, ""]
    if not globals_:
        out += ["# No global remaps yet — add one with `omarchy-key-remap add`.", ""]
        return "\n".join(out)

    # keyd requires a composite layer to come after the layers it is made of, so
    # order by how many modifiers a layer names; [main] always leads.
    for name in sorted(sections, key=lambda n: (n != "main", n.count("+"), n)):
        out.append(f"[{name}]")
        out.append("")
        for r, key, action in sections[name]:
            if r.note:
                out.append(f"# {r.note}")
            out.append(f"{key} = {action}")
        out.append("")
    return "\n".join(out)


def bindings_for_app(remaps: list[Remap], app: str) -> list[str]:
    """The `keyd bind` expressions that apply while `app` is focused.

    Matching is case-insensitive on the window class, because "Chromium" from the
    compositor and "chromium" from the person are meant to be the same thing.
    """
    want = (app or "").strip().lower()
    return [binding(r.validate()) for r in remaps if r.app and r.app.strip().lower() == want]


def apps(remaps: list[Remap]) -> list[str]:
    """Every window class any remap mentions, in first-seen order."""
    seen: list[str] = []
    for r in remaps:
        if r.app and r.app not in seen:
            seen.append(r.app)
    return seen
