"""The parts that need root: validating, installing and reloading keyd's config.

/etc/keyd/default.conf is the only file touched, it is never written without
`keyd check` passing first, and a config that was not written by this tool is
backed up before it is replaced.
"""
from __future__ import annotations

import datetime
import os
import shlex
import shutil
import subprocess
import sys
import tempfile

from .config import KEYD_CONF

MARKER = "Generated by omarchy-key-remap"


class PrivilegeError(Exception):
    pass


def keyd_installed() -> bool:
    return shutil.which("keyd") is not None


def check(text: str) -> tuple[bool, str]:
    """Ask keyd itself whether this config parses. No keyd, no verdict — and we say so."""
    if not keyd_installed():
        return True, "keyd is not installed, so the config could not be checked"
    with tempfile.TemporaryDirectory() as d:
        path = os.path.join(d, "default.conf")
        with open(path, "w", encoding="utf-8") as f:
            f.write(text)
        r = subprocess.run(["keyd", "check", path], capture_output=True, check=False)
        out = (r.stdout + r.stderr).decode("utf-8", "replace").strip()
        return r.returncode == 0, out


def elevator() -> list[str]:
    """How to become root: sudo on a terminal, pkexec from a menu.

    One asks in the terminal you are already looking at, the other draws the password
    dialog the desktop already has. $OMARCHY_KEY_REMAP_ELEVATOR overrides both, for
    doas, for a passwordless setup, or for a test harness.
    """
    override = os.environ.get("OMARCHY_KEY_REMAP_ELEVATOR")
    if override:
        return shlex.split(override)
    if os.geteuid() == 0:
        return []
    if sys.stdin.isatty() and shutil.which("sudo"):
        return ["sudo"]
    for candidate in ("pkexec", "sudo", "doas"):
        if shutil.which(candidate):
            return [candidate]
    raise PrivilegeError("none of pkexec, sudo or doas is available")


def install(text: str, reload: bool = True, target: str = KEYD_CONF) -> None:
    """Put the config in place (backing up a foreign one) and reload keyd."""
    ok, message = check(text)
    if not ok:
        raise PrivilegeError(f"keyd rejected the generated config:\n{message}")

    stamp = datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
    fd, tmp = tempfile.mkstemp(prefix="omarchy-key-remap.", suffix=".conf")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            f.write(text)
        os.chmod(tmp, 0o644)
        script = (
            f'set -e\n'
            f'if [ -f "{target}" ] && ! grep -q "{MARKER}" "{target}"; then\n'
            f'  cp -a "{target}" "{target}.bak-{stamp}"\n'
            f'fi\n'
            f'install -Dm644 "{tmp}" "{target}"\n'
        )
        if reload:
            script += 'keyd reload || systemctl restart keyd\n'
        run_privileged(script)
    finally:
        try:
            os.unlink(tmp)
        except OSError:
            pass


def run_privileged(script: str) -> str:
    cmd = [*elevator(), "/bin/sh", "-c", script]
    r = subprocess.run(cmd, capture_output=True, check=False)
    if r.returncode != 0:
        detail = (r.stderr + r.stdout).decode("utf-8", "replace").strip()
        raise PrivilegeError(detail or f"the privileged step exited {r.returncode}")
    return r.stdout.decode("utf-8", "replace")


# ---------------------------------------------------------------- the keyd service

def service_state() -> dict[str, str]:
    def ask(*args: str) -> str:
        r = subprocess.run(["systemctl", *args], capture_output=True, check=False)
        return r.stdout.decode().strip() or r.stderr.decode().strip()
    return {"enabled": ask("is-enabled", "keyd"), "active": ask("is-active", "keyd")}


def in_keyd_group() -> bool:
    """Runtime bindings (the per-app remaps) talk to keyd's socket, which is group-owned."""
    try:
        import grp
        return "keyd" in [g.gr_name for g in grp.getgrall() if os.getlogin() in g.gr_mem] or \
               grp.getgrnam("keyd").gr_gid in os.getgroups()
    except (ImportError, KeyError, OSError):
        return False


def enable_service(add_to_group: str | None = None) -> None:
    script = "systemctl enable --now keyd\n"
    if add_to_group:
        script += f'usermod -aG keyd "{add_to_group}"\n'
    run_privileged(script)
